### ISSUE TITLE
TODO: the list

### ISSUE THREAD

**Issue by Chnapy** [Chnapy/youtube-album-uploader-multiple#1]
The most exhaustive possible.

- [ ] Clean the code (to be honest I have a small voice in my head that tells me to switch all the code to Typescript);
- [ ] Complete the --help command;
- [ ] Clean and complete the tests;
- [ ] Give the possibility to upload existing videos;
- [ ] Add support to some common extensions (wav, ogg, ...);
- [ ] Repair `--output=allinone`;
